name: Documentation Sync

on:
  push:
    branches:
    - main
    paths:
    - "docs/**"
  repository_dispatch:
    types: [docs]
  gollum:

env:
  GIT_AUTHOR_NAME: Actionbot
  GIT_AUTHOR_EMAIL: actions@github.com

jobs:
  job-sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Sync docs to wiki
      uses: newrelic/wiki-sync-action@main
      with:
        source: docs
        destination: wiki
        token: ${{ secrets.NEWRELIC_BOT_TOKEN }}
        gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
        gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
        commitMessage: "chore(docs): Sync $SOURCE to $DESTINATION"
  
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.NEWRELIC_BOT_TOKEN }} # allows us to push back to repo
        ref: main
    - name: Sync Wiki to Docs
      uses: newrelic/wiki-sync-action@main
      with:
        source: wiki
        destination: docs
        token: ${{ secrets.NEWRELIC_BOT_TOKEN }}
        gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
        gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
        branch: main # since default branch is develop in this example
        commitMessage: "chore(docs): Sync $SOURCE to $DESTINATION"
